[package]
name = "arb"
description = "◉ Arbitrary Protocols on top of Bitcoin (Bitcoin NFTs/Ordinals & Bitcoin Identities/Usernames)"
version = "0.2.0"
license = "GPL-3.0-only"
edition = "2021"
autotests = false
homepage = "https://github.com/tyjvazum/arb"
repository = "https://github.com/tyjvazum/arb"
autobins = false
rust-version = "1.67"

[workspace]
members = [".", "test-bitcoincore-rpc"]

[dependencies]
anyhow = { version = "1.0.56", features = ["backtrace"] }
axum = { version = "0.6.1", features = ["headers"] }
axum-server = "0.5.0"
base64 = "0.21.0"
bech32 = "0.9.1"
bip39 = "2.0.0"
bitcoin = { version = "0.29.1", features = ["rand"] }
boilerplate = { version = "0.2.3", features = ["axum"] }
brotli = "3.3.4"
chrono = "0.4.19"
clap = { version = "3.2.25", features = ["derive"] }
ctrlc = "3.2.1"
derive_more = "0.99.17"
dirs = "5.0.0"
env_logger = "0.10.0"
futures = "0.3.21"
hex = "0.4.3"
html-escaper = "0.2.0"
http = "0.2.6"
hyper = { version = "0.14.24", features = ["http1", "client"] }
include_dir = "0.7.3"
indicatif = "0.17.1"
lava_torrent = { version = "0.8.1" }
lazy_static = "1.4.0"
log = "0.4.14"
mime = "0.3.16"
mime_guess = "2.0.4"
miniscript = "9.0.1"
mp4 = "0.13.0"
ord-bitcoincore-rpc = "0.16.5"
redb = "0.13.0"
regex = "1.6.0"
rss = "2.0.1"
rust-embed = "6.4.0"
rustls = "0.21.1"
rustls-acme = { version = "0.7.1", features = ["axum"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81" }
serde_yaml = "0.9.17"
sys-info = "0.9.1"
tempfile = "3.2.0"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.9"
tokio-util = {version = "0.7.3", features = ["compat"] }
tower-http = { version = "0.4.0", features = ["compression-br", "compression-gzip", "cors", "set-header"] }
urlencoding = "2.1.2"
version-compare = "0.1.1"

[dev-dependencies]
executable-path = "1.0.0"
include_dir = "0.7.3"
pretty_assertions = "1.2.1"
reqwest = { version = "0.11.10", features = ["blocking"] }
test-bitcoincore-rpc = { path = "test-bitcoincore-rpc" }
unindent = "0.2.1"

[[bin]]
name = "arb"
path = "src/bin/main.rs"

[lib]
name = "arb"
path = "src/lib.rs"

[[test]]
name = "integration"
path = "tests/lib.rs"

[build-dependencies]
pulldown-cmark = "0.9.2"
